### ISSUE TITLE
Use Java exception or Vulkan error code in high-level command wrappers?

### ISSUE THREAD

**Issue by chuigda** [chuigda/vulkan4j#2]
Java exception
- Pros
  - More Java
  - Useful when you want to handle bunch of exceptions all at once
  - User doesn't have to check command by command
- Cons
  - Less "exact" mapping between Java and Vulkan
  - Increased code generation complexity
  - Bad when you want to handle exception one by one, or deliberately ignore some exceptions

**Comment by CousinZe** [comment]
LWJGL uses vulkan error code and that should be meaningful somehow. We just follow them.
