### ISSUE TITLE
Use `org.jetbrains.annotations.Nullable`?

### ISSUE THREAD

**Issue by chuigda** [chuigda/vulkan4j#22]
I'm thinking about using `org.jetbrains.annotations.Nullable` instead of our own `tech.icey.panama.annotation.nullable`. I'm unclear about Java world best practice yet. @ice1000 any suggestions?

**Comment by ice1000** [comment]
Use any well-known `@Nullable`. IDEs and static analysis tools understand it. Also Kotlin understands most well-known `@Nullable`. If you use your own then you can't take advantage of the tooling.
