### ISSUE TITLE
VkCube example

### ISSUE THREAD

**Issue by chuigda** [chuigda/vulkan4j#4]
A minimal VkCube example is required to examine our workout.

**Comment by CousinZe** [comment]
Wilco commander.

**Comment by CousinZe** [comment]
全体起立！

https://github.com/user-attachments/assets/d586c713-7323-49b6-b224-ced1bbda3f48

**Comment by ice1000** [comment]
牛逼

**Comment by chuigda** [comment]
Superceded by Vulkan Tutorial rewriting.

**Comment by chuigda** [comment]
https://vulkan4j.7dg.tech/tutorial/en/
Mission accomplished.
