### ISSUE TITLE
以数组作为参数的 Vulkan 命令

### ISSUE THREAD

**Issue by chuigda** [chuigda/vulkan4j#7]
[`vkCmdSetBlendConstants`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetBlendConstants.html) 的第二个参数是一个 `float[4]`，而 `FunctionDescriptor` 不接受形参具有 `SequenceLayout` 布局。目前 CZ 将其手动替换为 `ValueLayout.ADDRESS.withTargetLayout`，但我们暂且不知这对 ABI 有何影响。

**Comment by chuigda** [comment]
https://github.com/LWJGL/lwjgl3/blob/fce485130d250d5760d7286bde0de2caee27d8f3/modules/lwjgl/vulkan/src/generated/java/org/lwjgl/vulkan/VK10.java#L10741-L10742

![图片](https://github.com/user-attachments/assets/d145b9df-1c5d-48f5-aabf-d9dd4b4c61ca)

![图片](https://github.com/user-attachments/assets/d889a906-0725-4196-b7de-f174aee81b46)

LWJGL 直接用了指针。这里应该不会有问题。

**Comment by CousinZe** [comment]
Fixed in https://github.com/chuigda/vulkan4j/commit/4eb8311ef62e2c213110e818db93caa2267353c4
